version: 1
preset: node-lib
checks:
  required: [ci, test]
  license:
    deny: [GPL-2.0, GPL-3.0]
  security:
    audit_level: low
    dependency_review: true
    codeql: true
    sbom: true
    slsa_provenance: true
    ossf_scorecard: true
pr_feedback:
  enabled: true
  mode: aggregated
  flaky_hints: true
branches:
  protected: [main]
