version: 1
preset: node-lib
checks:
  required: [ci, test]
  license:
    deny: [GPL-2.0, GPL-3.0]
  security:
    audit_level: critical
    dependency_review: true
    codeql: false
    sbom: true
    slsa_provenance: false
    ossf_scorecard: false
pr_feedback:
  enabled: true
  mode: aggregated
  flaky_hints: true
branches:
  protected: [main]
